version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env      
    environment:
      VIRTUAL_HOST: contract-registry-stg.gameficap.com
      LETSENCRYPT_HOST: contract-registry-stg.gameficap.com
      LETSENCRYPT_EMAIL: admin@royalprotocol.io
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "10"
